### PR TITLE
Introduce Linting-Step in Build

### PR DESCRIPTION
**Pull request by cimnine**
Related Issue: n/a

## New Behavior

The `.editorconfig` file instructs [compatible file editors and IDEs](https://editorconfig.org/#download) to correctly format the files in this repository.
The new `linter` job automatically checks for common issues in contributed code.

## Contrast to Current Behavior

File editors and IDEs use whatever default they either infer or are set up with to format files.
We have to check all code ourselves and remind ourselves of common practices in the community.

## Discussion: Benefits and Drawbacks

This change won't liberate us maintainers from checking the formatting of proposed changes, but it should make more such changes be suggested in a correct format. It will also help ourselves to adhere to our guideline by configuring our own file editors or IDEs to respect the `.editorconfig` and other linting rules.

But I strongly believe that it's sometimes ok to violate a linter rule. This can be discussed on a case-by-case base in the PR if it's not for obvious reasons.

## Changes to the Wiki

n/a

## Proposed Release Note Entry

n/a

## Double Check

* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

### CODE REVIEW

**Comment by tobiasge** [comment]
We could go one step further and also add the following things:
```
[startup_scripts/**.py]
indent_size = 4
profile = black
```

And one more file named `pyproject.toml`:
```toml
[tool.black]
line-length = 100
target-version = ['py38']
```

That way our script files can be formatted with [black](https://black.readthedocs.io/en/stable/).

**Comment by cimnine** [comment]
This PR went a little out-of-hand 🙈 I've integrated [Github's _super-linter_](https://github.com/github/super-linter/). It will use the common linters for various technologies.

It's configured to only check the files that have changed in a specific PR.

Unfortunately I have one problem that I can't get my head around and which annoys me: I would like _black_ to ignore the `configuration` directory entirely, since I would like to keep it's formatting as close as possible to [the upstream format](https://github.com/netbox-community/netbox/blob/19844e81d115c3a9a2798b03d5c09eb29c218a5c/netbox/netbox/configuration.example.py), which makes it easier to diff for added and removed variables.

@tobiasge any idea how I could teach this trick to _black_?

PS: To test locally, I've used the following command. But I was still not able to figure out black's syntax to ignore the `configuration` directory:

```bash
docker run \
  -v "$PWD:/tmp/lint" \
  -e 'RUN_LOCAL=true' \
  -e 'FILTER_REGEX_EXCLUDE=.*\.netbox.*' \
  -e 'LINTER_RULES_PATH=./' \
  -e 'VALIDATE_DOCKERFILE=false' \
  -e 'PYTHON_BLACK_CONFIG_FILE=pyproject.toml' \
  -e 'PYTHON_ISORT_CONFIG_FILE=pyproject.toml' \
  github/super-linter
```

**Comment by tobiasge** [comment]
I think the problem is, that the image is calling black for every file directly. You could exclude the files with the regex:
`-e 'FILTER_REGEX_EXCLUDE='.*\.netbox.*'|.*configuration.py|.*ldap_config.py|LICENSE' \`

**Comment by cimnine** [comment]
Thanks @tobiasge, I totally missed at I can ignore on the level of super-linter itself in the GH Action workflow as well.

There's one linting issue left, which I suggest to ignore, because afaict it's a _false positive_. Since the linter only checks files that are modified in a PR, this issue should not bother anyone unless `startup_scripts/310_secret_roles.py` is touched.

**Review by tobiasge — APPROVED** [review]

**Pull request merged**
