### PR TITLE
Adding REF to GitHub repo HEAD for cache busting

### PR DESCRIPTION
**Pull request by rje6459**
After installing requirements, check if  HEAD has changed and bust cache for RUN instruction for wget  archive

### CODE REVIEW

**Comment by cimnine** [comment]
Interesting approach!

**Comment by cimnine** [comment]
One problem is though that there is no generic way to make it work with tags:

```
https://api.github.com/repos/digitalocean/netbox/git/refs/heads/master ✔️ 
https://api.github.com/repos/digitalocean/netbox/git/refs/heads/v2.5.12 ❌
https://api.github.com/repos/digitalocean/netbox/git/refs/tags/v2.5.12 ⚠️
```

**Comment by rje6459** [comment]
A possible workaround to that would be to just query `https://api.github.com/repos/digitalocean/netbox/git/refs` and if **any** HEAD or TAG changes to redownload the netbox archive. This solution definitely isn't optimal especially if other refs are being worked on at the same time.

Another option would be to change the archive download REF_URL to https://api.github.com/repos/digitalocean/netbox/contents?ref=v2.5.12, which would work with both heads and tags and should have the same functionality

**Comment by cimnine** [comment]
This was manually merged in a5537b18a470b7481dca6e632f1904d3a4499006. Thanks for the PR!

**Pull request closed without merging**
