### PR TITLE
Add xmlsec with no-binary option

### PR DESCRIPTION
**Pull request by lchastel**
SAML backend is still not working.
I have the issue  "lxml & xmlsec libxml2 library version mismatch".

Related Issue:

## New Behavior

Adding xmlsec to requirements-container.txt for python3-saml like it's done for lxml solve the issue.

## Contrast to Current Behavior

When enabling SAML backend, I receives the error message 
     lxml & xmlsec libxml2 library version mismatch

How to reproduce ?
* Follow Quickstart of netbox-docker
* Add next lines to env/netbox.env
`REMOTE_AUTH_BACKEND='social_core.backends.saml.SAMLAuth'`
`DEBUG=true`

* Start or restart netbox
`docker compose up -d`
* Connect to the netbox instance (you may have to click on login)
   Here is the result ...
saml_netbox

## Discussion: Benefits and Drawbacks

...

## Changes to the Wiki

...

## Proposed Release Note Entry

...

## Double Check

* [X] I have read the comments and followed the PR template.
* [X] I have explained my PR according to the information in the comments.
* [X] My PR targets the `develop` branch.

### CODE REVIEW

**Comment by cimnine** [comment]
Thanks for the PR. This looks fine to me, what do you think @tobiasge ? @lchastel could you update your PR with the latest changes from the `develop` branch?

**Review by tobiasge — APPROVED** [review]

**Comment by jonlarsdizparc** [comment]
@cimnine Should this fix be automatically updated into new docker hub builds? I'm still experiencing these issues on version [v4.0.5-2.9.1](https://hub.docker.com/layers/netboxcommunity/netbox/v4.0.5-2.9.1/images/sha256-c263c3f09a8c64089877ba0515549fbb863a79eaee7e47d253086d4aebe8750a?context=explore) (updated 2 days ago).

**Comment by cimnine** [comment]
It will be when we release a new version of the NB Docker project. (That's the 2.9.1 part of the tag)

**Comment by lchastel** [comment]
If you need the correction, you could temporary use my image, docker pull ghcr.io/lchastel/netbox-docker:snapshot-2.9.1
I made it 4 days ago, from develop branch.

@cimnine : Could you please check the Github Actions workflow ? (cf https://github.com/netbox-community/netbox-docker/discussions/1258)
              Except if I made a mistake, the job "Builds new NetBox Docker Images (./build.sh develop, ubuntu-latest)" should create a new image from develop branch and push it as snapshot (or snapshot-2.9.1) ... but the file /opt/netbox/requirements-container.txt is the one from release branche.
            I checked on latest workflow "Merge pull request #1260 from netbox-community/renovate/sentry-sdk-2.x #1440"           
           I also pull the latest image with snapshot from dockerhub (docker pull netboxcommunity/netbox:snapshot)
              sha256:59f03c3086462aea7c435ffb057575ace74098a960cd9567bfd27418bf563102
           The image does not contains the file /opt/netbox/requirements-container.txt in version of develop branch.

**Comment by jonlarsdizparc** [comment]
> If you need the correction, you could temporary use my image, docker pull ghcr.io/lchastel/netbox-docker:snapshot-2.9.1 I made it 4 days ago, from develop branch.

Thank you! I'll use it until the next version has been published.

**Pull request merged**
