### PR TITLE
Release 2.4.0

### PR DESCRIPTION
**Pull request by tobiasge**
Related Issue: -

## New Behavior
- Release 2.40

## Contrast to Current Behavior
- None

## Discussion: Benefits and Drawbacks
- None

## Changes to the Wiki
- None

## Proposed Release Note Entry

# Noteworthy Changes

## Update postgres Docker tag to v15 #865

Our docker-compose file was updated to use PostgreSQL 15.

**Note that you will need to take manual action after you upgrade a live PostgreSQL database.**
If your database is not too big, a full backup (with PostgreSQL 14, i.e. before the upgrade) and restore (with a clean PostgreSQL 15, i.e. after the upgrade) is probably the easiest to achieve. Our [troubleshooting wiki page][wiki-troubleshooting] has instructions on how to backup and restore a Netbox database. **Please test the procedure on a test system first!**

[wiki-troubleshooting]: https://github.com/netbox-community/netbox-docker/wiki/Troubleshooting#docker-compose-basics

Note that there is no requirement to update to PostgreSQL 15, you can stick to version 14 just fine. You could do this with a `docker-compose.override.yml` like so:

```yaml
version: '3.4'
services:
  postgres:
    image: postgres:14-alpine
```

## Added settings for CA certificates for LDAP #895
The new settings LDAP_CA_CERT_* can now be configured in environment variables

## Optimize psycopg2 dependency #894
We install only one version of psycopg2

## Startup scripts complete removal #893
All warnings regarding the old startup scripts were removed

## Make nginx-unit listen on IPv4 and IPv6 #889
The container can now be used with IPv6.

## Housekeeping var name fix #883
This fixed a bug were the housekeeping job was not run in the correct interval

## Add requirements for SAML SSO #876
All Python requirements for SAML authentication are now installed per default

## Address housekeeping traceback #866
This changes the startup order of the containers in the example compose file, which prevents a crash in the housekeeping job when the database was not yet initialised

## Updates the configuration, changes default for dynamic parameters to None #857
All dynamic parameters can now be set correctly in the Netbox GUI when they aren't defined in environment variables.

## Define a volume for the caching Redis #852
To prevent docker from creating new random volumes every time the containers are started, we now define a fixed volume for both Redis containers.

## add JOBRESULT_RETENTION to configuration.py #840
`JOBRESULT_RETENTION` can now be set from an environment variable

# Compatibility

This version of NetBox Docker is only compatible with NetBox v3.4.x and above.
For older versions, use [a previous release of NetBox Docker](https://github.com/netbox-community/netbox-docker/releases/).

## Double Check
* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [ ] My PR targets the `develop` branch.

### CODE REVIEW

**Review by cimnine — APPROVED** [review]

**Comment by cimnine** [comment]
Thank you for bundling the release

**Comment by tagur87** [comment]
Is it possible to also update nginx-unit to 1,29 in this release? It includes a fix we need for large header size.

https://github.com/nginx/unit/commit/edd7ebaf60feb00a5bb996c73ce2de41fa4cf6cc

Ref: https://github.com/netbox-community/netbox-docker/issues/875

**Comment by tobiasge** [comment]
> Is it possible to also update nginx-unit to 1,29 in this release? It includes a fix we need for large header size.
> 
> [nginx/unit@edd7eba](https://github.com/nginx/unit/commit/edd7ebaf60feb00a5bb996c73ce2de41fa4cf6cc)
> 
> Ref: #875

An update to Nginx Unit will need more testing. As of now the new release is not yet on their Ubuntu package mirror, so it will have to wait.

**Comment by tagur87** [comment]
Thanks @tobiasge!

Looks like it's available now on ubuntu mirror. 

Can you assist in getting this released? Or should I create an issue?

```
/# apt install unit=1.29.0-1~jammy
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  unit
...
Unpacking unit (1.29.0-1~jammy) ...
Setting up unit (1.29.0-1~jammy) ...
```

**Comment by tobiasge** [comment]
I already started with some test but ran into an issue with our configuration files, thats new in 1.29 vs some tests with 1.28.
You can follow that [here](https://mailman.nginx.org/pipermail/unit/2022-December/CTHXK37SGZICG2KTFCTURYYSZWUO74FK.html).

**Comment by tagur87** [comment]
Thanks Tobias, 

I see that they have found a commit that causing the issue. Are we going to need to wait for another release of unit? Or is it something that can be patched in this repo?

**Pull request merged**
