### PR TITLE
Set restart policy to always for all containers

### PR DESCRIPTION
**Pull request by billchenchina**
## New Behavior

Set restart policy to always for all containers.

## Contrast to Current Behavior

Service won't start if docker restarts.

## Changes to the Wiki

Will update if essential.

## Proposed Release Note Entry

```
Set restart policy to always by default.

Currently, netbox won't launch automatically after a previous halt. This
release changed the restart policy to always by default.
```

## Double Check

* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

### CODE REVIEW

**Comment by cimnine** [comment]
You can use the `docker-compose.override.yaml` to set a restart policy.

**Comment by billchenchina** [comment]
> You can use the `docker-compose.override.yaml` to set a restart policy.

Sure.

I would recommend adding the restart policy to `always` by default.
Also, adding default policies to `docker-compose.override.yaml.example` is also ok.

**Comment by ryanmerolle** [comment]
@billchenchina are you updating this PR per @cimnine suggestion or should we close this?

**Comment by netsandbox** [comment]
A better restart policy would be `unless-stopped` instead of `always`: https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy

`unless-stopped` prevents containers from starting on Docker daemon restart, if they where previously stopped manually.

**Comment by tobiasge** [comment]
As mentioned above  `always` is not a good default and this should be set in the `docker-compose.override.yaml` file.

The wiki is open to edit so you can start a section with `docker-compose.override.yaml` examples.

**Pull request closed without merging**
