### PR TITLE
Add redis username parameter

### PR DESCRIPTION
**Pull request by christianpinger**
Related Issue: N/A

## New Behavior

NetBox 3.4.2 introduced a redis username parameter. This PR will add an optional redis username parameter, to support environments where a username is required.

## Contrast to Current Behavior

No redis username can be configured.

## Discussion: Benefits and Drawbacks

* Users can now configure a redis username
* There are no drawbacks
* The change is fully backwards compatible, the parameter is optional

## Proposed Release Note Entry

Add redis username configuration parameter.

## Double Check

* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

### CODE REVIEW

**Review by cimnine — APPROVED** [review]
Thanks for the PR. This lgtm. @tobiasge, wdyt?

**Comment by cimnine** [comment]
One more thought: Would it make a difference if the default value would be `None` instead of the empty string?

**Comment by christianpinger** [comment]
@cimnine I've not tested this with `None`, but NetBox itself uses empty strings as default values, so I've done the same.

**Comment by cimnine** [comment]
Perfect.

**Pull request merged**
