### PR TITLE
add missing REMOTE_AUTH config options

### LINKED ISSUE #992: Some REMOTE_AUTH_ settings missing
### Desired Behavior

I'd like to be able to provide all the [Remote Auth](https://github.com/netbox-community/netbox/blob/develop/docs/configuration/remote-authentication.md) settings as environment variables.

### Contrast to Current Behavior

Currently only 
```
REMOTE_AUTH_ENABLED
REMOTE_AUTH_BACKEND
REMOTE_AUTH_HEADER
REMOTE_AUTH_AUTO_CREATE_USER
REMOTE_AUTH_DEFAULT_GROUPS
```
are able to be pulled in from environment variables

### Required Changes

Adding the ability to declare the other environment variables.

### Discussion: Benefits and Drawbacks

I'm aware that I can do it currently by adding an extra file to the configuration folder but it would be good to not have to mount an extra file into the container.

Also aware that `REMOTE_AUTH_DEFAULT_PERMISSIONS` isn't recommended due to the complexity of the value - ref https://github.com/netbox-community/netbox-docker/issues/890 - but that shouldn't preclude the other variables from being made available.

### PR DESCRIPTION
**Pull request by hendrikbl**
Related Issue: #992 

## New Behavior

All `REMOTE_AUTH` condifuration settings are now configurable via environment variables.
A list of all available options can be found here: https://github.com/netbox-community/netbox/blob/develop/docs/configuration/remote-authentication.md

## Contrast to Current Behavior

Currently only the following optiosn are configurable via environment variables:
```
REMOTE_AUTH_ENABLED
REMOTE_AUTH_BACKEND
REMOTE_AUTH_HEADER
REMOTE_AUTH_AUTO_CREATE_USER
REMOTE_AUTH_DEFAULT_GROUPS
```

## Discussion: Benefits and Drawbacks

This change makes configuration more consistent since most of the configuration should be done in `.env` files if possible.

## Changes to the Wiki

None

## Proposed Release Note Entry

Make all `REMOTE_AUTH` config options configurable via environment variables

## Double Check

* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

### CODE REVIEW

**Comment by tobiasge** [comment]
Please use the provided PR template an target the develop branch.

**Comment by hendrikbl** [comment]
> Please use the provided PR template an target the develop branch.

Oh sorry, don't know how I messed this up. I updated the PR with the correct template.

**Comment by empusas** [comment]
Why not also include the most common SSO integrations variables as suggested in this issue:
https://github.com/netbox-community/netbox-docker/issues/1139

**Comment by hendrikbl** [comment]
> Why not also include the most common SSO integrations variables as suggested in this issue: #1139

I'm not sure if it's a good idea to knowingly put only a few configuration parameters for `SOCIAL_AUTH_` in there. I think it leads to confusion if some of them are configured via env and some are not.
But that's something the maintainers have to decide I guess @tobiasge

**Review by cimnine — APPROVED** [review]
Thanks for the PR. This lgtm.

**Pull request merged**
