### PR TITLE
preentry script - allows for easily installing development plugins etc

### PR DESCRIPTION
**Pull request by ITJamie**
Related Issue:

## New Behavior

a pre-entry script that runs before all other scripts during container start. 
Allows users to quickly add modifications before anything else runs inside the container. 
Particularly useful to install local development plugins or to use `sed` commands to modify a file in the image without having to map the whole file.

## Contrast to Current Behavior

Removes the requirement to have a custom dockerfile to achieve quick modifications inside the container 

## Discussion: Benefits and Drawbacks

I have been running this for a few days. It allows users to easily add additional local packages into the container without having to have their own dockerfile. 

It is particularly useful for local plugin development as you can map a plugin folder to a directory inside the container and install it during container start.

If a user needs to modify a few lines in a file its quite quick and usually more upgrade safe than managing the whole file with a volume mount

Drawbacks: If users add a lot to this script it can slow container startup time. 

## Changes to the Wiki

Additional documentation would be needed if this is deemed acceptable

## Proposed Release Note Entry

...

## Double Check

* [X] I have read the comments and followed the PR template.
* [X] I have explained my PR according to the information in the comments.
* [X] My PR targets the `develop` branch.

### CODE REVIEW

**Comment by kkthxbye-code** [comment]
From a cursory glace I'm a little confused. 

For the housekeeping service you are triggering the script through the existing housekeeping.sh. For the worker service you are triggering it by changing the command in the compose file. For the main netbox service you are not running the script at all as far as I can tell.

Is this unfinished, or did you miss something? At the very least, the method of execution should be the same for all services.

In general I'm not sure I like this approach at all - runtime post-launch installation in containers seem like an anti-pattern.

**Comment by ITJamie** [comment]
@kkthxbye-code nice catch I forgot to add it to the docker-entrypoint.sh script for the main netbox runner. I pushed another commit there to fix that

As for the queue-worker. I find that particular setup a bit odd of the 3 containers. I personally think a `launch-worker.sh` script that takes a single variable or env var for its queue would "fit" into docker-style-ism

As for wether this is an overall docker antipattern. Ive seen this concept in a lot of containers. Eg 
- postgres/mariadb etc with its initdb.d folder which can run sql files or .sh scripts
- Bitnami's images typically allow this or the supplying of a set of external requirements, eg pip requirements.txt to install pre service start or just a dir to add .sh files into
- linuxserver.io has its "docker mods" setup that adds an overlay of mods at the start of a container. eg https://github.com/linuxserver/docker-mods/tree/universal-package-install

The main point though, It's use is entirely optional and upto the community. 
Personally i like the flexibility to quickly mod files or packages in a container without having to maintain a dockerfile or manage a whole file with a volume mount. 

With this modification, users can now use a volume mount to override `preentry.sh` with a script that can handle any needed modifications inside the container. No other adjustments needed.

**Comment by ITJamie** [comment]
@kkthxbye-code is there anything else you would need see added to this pr or discussion somewhere?

**Comment by kkthxbye-code** [comment]
@tobiasge or @cimnine would need to provide their input. My opinion is still that extending the image is the correct way to customize it.

**Comment by cimnine** [comment]
Thank you for this PR and your motivation to improve this project.

I believe I see where the intention for this scripts comes from. Yet I dislike the idea.

The main reason is that such a script introduces a nightmare for debugging a production instance. Because people will see this and believe that this is the way to add plugins to production instances, even though it's only intended for local plugin development. (The initializers were also intended for local development, but I'm certain there are now people relying on them for production purposes.)

And then, when an instance with your change breaks, there will have no reliable way to debug. Because the next time the container is started, it's installed packages may already look quite different. Worse, it might even prevent an instance from starting, because e.g. there's a temporary internet glitch of some sort and a `pip install` does not run through.

Furthermore, for most `pip install` and some `setup.py` invocations, C header files for the libraries are required. We don't include these in the final image to keep it reasonably slim. I'm certain that this will confuse unexperienced folks as well.

For these reason I'm very hesitant to consider this PR for inclusion.

**Comment by cimnine** [comment]
I will close this PR, since it's out of date and since the discussion stopped after my last comment.

**Pull request closed without merging**
