### PR TITLE
Fixes for Netbox 2.9

### PR DESCRIPTION
**Pull request by tobiasge**
Related Issue: #325

## New Behavior
- Startup scripts are compatible with changes made to Netbox 2.9

## Contrast to Current Behavior
- Startup scripts are failing 

## Proposed Release Note Entry
- Compatibility with Netbox 2.9

## Double Check

* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

### CODE REVIEW

**Review by Tavoons — APPROVED** [review]

**Review by olafz — APPROVED** [review]

**Comment by FragmentedPacket** [comment]
Is there anyway to get this merged in soon? I use this repo for development and testing on the Ansible modules and haven't been able to use the released 2.9 versions.

**Comment by clearly-tyler-whitney** [comment]
I have sent @cimnine an email regarding this PR, and suggested that they consider write permissions for other contributors.

**Comment by kkthxbye-code** [comment]
@jkuzma07 please let me know if you get a response. Forking the repo is another option.

**Review by cimnine — APPROVED** [review]
Thank you @tobiasge for the adjustments.

**Pull request merged**
