### PR TITLE
Make nginx-unit listen on IPv4 and IPv6

### LINKED ISSUE #887: daemon doesn't listen on IPv6
### Current Behavior

Even if the Docker container has IPv6 enabled, the daemon isn't listening on it, requiring the use of IPv4:

```
[0 root@durnik ~] docker container inspect netbox-netbox-1 | rg 'IPAddress|GlobalIPv6Address' | tail -n 2
                    "IPAddress": "172.18.1.7",
                    "GlobalIPv6Address": "2a01:4f8:262:xxxx:a:b:c:d",
[0 root@durnik ~] telnet 172.18.1.7 8080
Trying 172.18.1.7...
Connected to 172.18.1.7.
Escape character is '^]'.
HTTP/1.1 400 Bad Request
Content-Type: text/html
Server: Unit/1.27.0
Date: Sun, 20 Nov 2022 00:25:50 GMT
Content-Length: 54
Connection: close

<!DOCTYPE html><title>Error 400</title><p>Error 400.
Connection closed by foreign host.
[1 root@durnik ~] telnet 2a01:4f8:262:xxxx:a:b:c:d 8080
Trying 2a01:4f8:262:xxxx:a:b:c:d...
telnet: Unable to connect to remote host: Connection refused
```

Actual IPv6 obscured.

### Expected Behavior

I would expect the daemon to listen on both IPv4 and IPv6.

### Docker Compose Version

2.12.2

### Docker Version

```text
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:49 2022
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### The git Revision

8b16b16e45ca88506521ca03de9320d07ec8e9ed

### The git Status

```text
[0 root@durnik (release) /srv/docker-compose/netbox] git st
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean
```
```


### Startup Command

docker compose up -d

### NetBox Logs

```text
netbox-netbox-1  | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-netbox-1  | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-netbox-1  | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-netbox-1  | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-netbox-1  | 💡 Superuser Username: admin, E-Mail: admin@example.com
netbox-netbox-1  | ⚠️⚠️⚠️ WARNING: The initializers have been moved to a plugin. See release notes.
netbox-netbox-1  | ⚠️⚠️⚠️ Set environment variable 'SKIP_STARTUP_SCRIPTS' to 'true' to remove this warning.
netbox-netbox-1  | ✅ Initialisation is done.
netbox-netbox-1  | ⏳ Waiting for control socket to be created... (1/10)
netbox-netbox-1  | 2022/11/20 00:32:08 [warn] 6#6 Unit is running unprivileged, then it cannot use arbitrary user and group.
netbox-netbox-1  | 2022/11/20 00:32:08 [info] 6#6 unit 1.27.0 started
netbox-netbox-1  | 2022/11/20 00:32:08 [info] 13#13 discovery started
netbox-netbox-1  | 2022/11/20 00:32:08 [notice] 13#13 module: python 3.10.4 "/usr/lib/unit/modules/python3.10.unit.so"
netbox-netbox-1  | 2022/11/20 00:32:08 [info] 6#6 controller started
netbox-netbox-1  | 2022/11/20 00:32:08 [info] 15#15 router started
netbox-netbox-1  | 2022/11/20 00:32:08 [notice] 6#6 process 13 exited with code 0
netbox-netbox-1  | 2022/11/20 00:32:08 [info] 15#15 OpenSSL 3.0.2 15 Mar 2022, 30000020
netbox-netbox-1  | ⚙️ Applying configuration from /etc/unit/nginx-unit.json
netbox-netbox-1  | 2022/11/20 00:32:10 [info] 19#19 "netbox" prototype started
netbox-netbox-1  | 2022/11/20 00:32:10 [info] 20#20 "netbox" application started
netbox-netbox-1  | ✅ Unit configuration loaded successfully
netbox-netbox-1  | 2022/11/20 00:32:11 [notice] 6#6 process 11 exited with code 0
```

### Content of docker-compose.override.yml

```yaml
services:
  netbox:
    ports:
      - 8100:8080
    networks:
      - netbox

  netbox-worker:
    networks:
      - netbox

  netbox-housekeeping:
    networks:
      - netbox

  postgres:
    networks:
      - netbox

  redis:
    networks:
      - netbox

  redis-cache:
    networks:
      - netbox

networks:
  netbox:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "172.18.1.0/24"
        - subnet: "2a01:4f8:262:xxxx:a::/80"
```

### PR DESCRIPTION
**Pull request by cimnine**
Related Issue: #887 

## New Behavior

Nginx Unit listens on IPv4 and IPv6.

## Contrast to Current Behavior

It seems that `*:8080` only binds to `0.0.0.0:8080`, unfortunately.

## Discussion: Benefits and Drawbacks

I don't see any drawbacks.

## Changes to the Wiki

n/a

## Proposed Release Note Entry

The container will now also listen on IPv6.

## Double Check

* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

### CODE REVIEW

**Review by tobiasge — APPROVED** [review]

**Comment by bsv9** [comment]
This configurations doesn't work if on system with ipv6 disabled

```
⚙️ Applying configuration from /etc/unit/nginx-unit.json
2022/12/15 16:56:44 [alert] 7#7 socket(\"[::]:8080\") failed (97: Address family not supported by protocol)
2022/12/15 16:56:44 [alert] 23#23 failed to apply new conf
```

How to repeat:
Add "ipv6.disable=1" to the kernel args

**Comment by mlazzarotto** [comment]
> This configurations doesn't work if on system with ipv6 disabled
> 
> ```
> ⚙️ Applying configuration from /etc/unit/nginx-unit.json
> 2022/12/15 16:56:44 [alert] 7#7 socket(\"[::]:8080\") failed (97: Address family not supported by protocol)
> 2022/12/15 16:56:44 [alert] 23#23 failed to apply new conf
> ```
> 
> How to repeat: Add "ipv6.disable=1" to the kernel args

I confirm this behaviour. Not everyone has IPv6 enabled

**Comment by chrisho95** [comment]
Hi,

I have the same problem. I don't use IPv6 adresses.

2023/01/10 13:50:17 [notice] 7#7 process 14 exited with code 0
2023/01/10 13:50:17 [info] 16#16 router started
2023/01/10 13:50:17 [info] 16#16 OpenSSL 3.0.2 15 Mar 2022, 30000020
âï¸ Applying configuration from /etc/unit/nginx-unit.json
2023/01/10 13:50:18 [alert] 7#7 socket("[::]:8080") failed (97: Address family not supported by protocol)
2023/01/10 13:50:18 [alert] 16#16 failed to apply new conf
â ï¸ Could no load Unit configuration
2023/01/10 13:50:18 [notice] 7#7 process 12 exited with code 1
2023/01/10 13:50:18 [notice] 7#7 process 15 exited with code 0
2023/01/10 13:50:18 [notice] 7#7 process 16 exited with code 0

To work around this problem, I have to overwrite the nginx-unit.json file by removing the ipv6 part. All done in my docker-compose file.

**Comment by CupcakePWR** [comment]
> I have to overwrite the nginx-unit.json file by removing the ipv6 part. All done in my docker-compose file.

Mind sharing how you did that? I'm having the same problem, and I'm not _that_ familiar with docker

**Comment by chrisho95** [comment]
Hi,

You need to put your "nginx-unit.json" file in a directory on your server and remove the ipv6 part. Then in your docker-compose file, you must create a volume between your corrected file and the file that is placed in the docker (foler /etc/unit/).

Finally you have to launch the commande "docker-compose up -d" to rebuild the docker.

version: '3.4'
services:
  netbox-rms: &netbox-rms
    image: netbox-docker:v3.4.1
    container_name: netbox-rms
    restart: unless-stopped
    depends_on:
    - redis-rms
    - redis-cache-rms
    - netbox-worker-rms
    env_file: /opt/netbox/env/netbox.env
    user: 'unit:root'
    volumes:
    - netbox-media-files:/opt/netbox/netbox/media:z
    - /opt/netbox/configuration:/etc/netbox/config:z,ro
    - /opt/netbox/scripts:/etc/netbox/scripts:z,ro
    - **/opt/netbox/configuration/nginx-unit.json:/etc/unit/nginx-unit.json:ro**

Br,

Chris.

**Comment by CupcakePWR** [comment]
My biggest headache was how to get the nginx-unit.json file out from my container when it wouldn't boot.. 
But I copied the nginx-unit.json from [here](https://github.com/netbox-community/netbox-docker/blob/release/docker/nginx-unit.json) to ./configuration/nginx-unit.json and removed this;
   "[::]:8080": {
      "pass": "routes"
    }
   
Then changed my docker-compose.override.yml file as you suggested and ran docker-compose up -d 
It works again now! Thanks!

**Pull request merged**
