### PR TITLE
Plugin

### PR DESCRIPTION
**Pull request by pv2b**
Related Issue:

## New Behavior

Currently, [the instructions to about using netbox-docker with plugins](https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins) have users create and modify files inside the git repository. This isn't great because anyone following these instructions as it will end up with a repository with untracked changes, which, in addition to being "dirty" may cause problems down the line when pulling in new updates to the repo.

...

## Contrast to Current Behavior

The new solution is to check the documentation samples in as "example" files, that the user will then be able to cp in place as "real" files to then copy, in case they decide to use plugins. The .gitignore file is updated to allow the user to keep these files local and not in the repo.

As an exception, the Dockerfile-Plugins file has been checked in outright, since that will typically not require any local changes, so it can just live in the repo.

...

## Discussion: Benefits and Drawbacks

By making this change, it'll be easier for administrators to run Netbox-docker with plugins without polluting their repositories with untracked changes, which will let them easier update to new versions of netbox-docker.

As for backwards-compatibility, I've not tested this scenario extensively, but I believe there'd be a problem trying to pull new commits for existing users that have a modified plugins.py file, because suddenly configuration/plugins.py is "deleted" but also put in .gitignore, I'm not sure what happens to the local file in such a case. (Ironically, this kind of problem is exactly what this PR is intended to avoid in the first place.)

The workaround would be to copy away the plugins.py file somewhere else temporarilly, pull, and then put it back.

...

## Changes to the Wiki

[The instructions to about using netbox-docker with plugins](https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins) will need to be updated. Specifically, we can probably remove some example code from the documentation page itself and just refer to the files in the repo. The chapter on Dockerfile-Plugins can likely be completely removed.

...

## Proposed Release Note Entry

Added example configuration for building custom Netbox images with plugins into the repositories, and added these file paths to `.gitignore`. Existing users trying to pull a new update may need to move their configuration/plugins.py file away temporarilly before pulling new commits to accomodate this change, and then put it back where it came from.

...

## Double Check

* [X] I have read the comments and followed the PR template.
* [X] I have explained my PR according to the information in the comments.
* [X] My PR targets the `develop` branch.

### CODE REVIEW

**Comment by cimnine** [comment]
The way to modify the files in the repo is just the quickest way to get going. You can use the image entirely without the files in the repo when you're familiar with Container technology. In fact, many do this to deploy NetBox Docker to Kubernetes.

The repo has proven to be a great quick start solution, where people have to do only little to get going. Using — or implementing plugins — is already an advanced use-case and indeed not a focus of the compose-based setup.

Besides that, you're free to create a commit of your changes in your local clone of the repo, and Git will (most of the time) do an amazing job at merging upstream changes with your local changes. (More so, if you rebase onto upstream instead of merging, as it preserves the original history.)

---

Everything that's in our repository needs to be maintained and is ideally tested — even better if automatically — with each release. I believe this is not something we want to commit ourselves to, but that's just my opinion.

**Comment by pv2b** [comment]
I can understand your position if you don't want to test the Plugin-Dockerfile and the examples. In that case, an alternative approach would be to simply removes the configuration/plugins.py files from the repo and add a few lines to .gitignore for the plugin-specific files. This would solve my same "itch" to use the repository as is.

**Comment by kkthxbye-code** [comment]
@pv2b - Can't you just call it plugin-custom.py or something else. Every .py file in that directory gets loaded.

**Comment by pv2b** [comment]
> @pv2b - Can't you just call it plugin-custom.py or something else. Every .py file in that directory gets loaded.

~Yes, as a matter of using the repo as is, that would "solve" the issue specifically with plugin.py, but that would still leave me with untracked files. I would argue that plugin.py doesn't belong in the repo though, and that if you don't want plugin stuff in the base repository, only in documentations, that file should just be deleted from the repo.~

**Comment by pv2b** [comment]
> @pv2b - Can't you just call it plugin-custom.py or something else. Every .py file in that directory gets loaded.

Actually, on second though, no. I can't use plugin-custom.py for this purpose, at least not with the Dockerfile-Plugin as currently listed in the Wiki.

See the following line in Dockerfile-Plugin:

```
COPY configuration/plugins.py /etc/netbox/config/plugins.py
```

Therefore, as the Dockerfile-Plugin is currently written in the docs, it depends on a file that the user is intended to change as configuiration, but also is explicitly excluded from .gitignore. Of course you could change the docs to not use plugins.py in future, but... better to just remove plugins.py

**Comment by pv2b** [comment]
I've given this some more thought, and I think this PR is trying to do too much at the same time. It confuses two distinct issues:

1. Sample code for plugins should be in the repository (and this seems to be controversial)
2. The `configuration/` directory does too many things.

I have some ideas about 2. I'll open up a seperate discussion about it where I expand on that, and I suggest we abandon this PR for now.

**Comment by cimnine** [comment]
> Actually, on second though, no. I can't use plugin-custom.py for this purpose, at least not with the Dockerfile-Plugin as currently listed in the Wiki.

What's stopping you from deriving your own the Dockerfile based on the one from our wiki? The wiki is community maintained. And that example helps people getting started, but it's not the only way to do things. If you believe the wiki would be better with another or a more elaborate example, feel free to improve the respective wiki page. I'm sure others will appreciate it as well.

**Comment by pv2b** [comment]
Since I'm not getting any traction on my discussion over at https://github.com/netbox-community/netbox-docker/discussions/1056 I'm going to conclude that the project isn't interested in restructuring the configuration to make it easy to keep the configuration out of the repo, and the repo status clean.

So I'm closing this and I'll consider maintaining my own fork of this repo for that purpose.

**Pull request closed without merging**
