### PR TITLE
Bugfix - Address issue #365

### PR DESCRIPTION
**Pull request by MajesticFalcon**
Related Issue: #365  

## New Behavior

Changed order in which scripts get loaded
...

## Contrast to Current Behavior

...

## Discussion: Benefits and Drawbacks

...

## Changes to the Wiki

...

## Proposed Release Note Entry

Adjusted initialization sequence to fix object prerequisites

## Double Check

* [X] I have read the comments and followed the PR template.
* [X] I have explained my PR according to the information in the comments.
* [X] My PR targets the `develop` branch.

### CODE REVIEW

**Review by cimnine — CHANGES_REQUESTED** [review]
Running the tests just failed in my environment:

```bash
./build-latest.sh && ./test.sh latest
```

results in

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/commands/shell.py", line 93, in handle
    exec(sys.stdin.read())
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/runpy.py", line 282, in run_path
    return _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "../startup_scripts/__main__.py", line 25, in <module>
    runpy.run_path(f.path)
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/netbox/startup_scripts/135_clusters.py", line 37, in <module>
    params[assoc] = model.objects.get(**query)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/cacheops/query.py", line 353, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
virtualization.models.DoesNotExist: ClusterGroup matching query does not exist.
```

Can you check this, please?

**Comment by cimnine** [comment]
You can take the chance to rebase this PR onto develop as well:

```bash
# add this repo as another remote
git remote add upstream https://github.com/netbox-community/netbox-docker.git
git fetch upstream

# update your develop branch from this repo
git switch develop
git pull -pr upstream/develop
git push # optional, push to your fork

# rebase your branch onto the latest changes in develop
git checkout iss365
git rebase develop
git push --force
```

**Comment by MajesticFalcon** [comment]
> Running the tests just failed in my environment:
> 
> ```shell
> ./build-latest.sh && ./test.sh latest
> ```
> 
> results in
> 
> ```
> Traceback (most recent call last):
>   File "./manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
>     output = self.handle(*args, **options)
>   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/commands/shell.py", line 93, in handle
>     exec(sys.stdin.read())
>   File "<string>", line 1, in <module>
>   File "/usr/lib/python3.8/runpy.py", line 282, in run_path
>     return _run_code(code, mod_globals, init_globals,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "../startup_scripts/__main__.py", line 25, in <module>
>     runpy.run_path(f.path)
>   File "/usr/lib/python3.8/runpy.py", line 265, in run_path
>     return _run_module_code(code, init_globals, run_name,
>   File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/opt/netbox/startup_scripts/135_clusters.py", line 37, in <module>
>     params[assoc] = model.objects.get(**query)
>   File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/opt/netbox/venv/lib/python3.8/site-packages/cacheops/query.py", line 353, in get
>     return qs._no_monkey.get(qs, *args, **kwargs)
>   File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
>     raise self.model.DoesNotExist(
> virtualization.models.DoesNotExist: ClusterGroup matching query does not exist.
> ```
> 
> Can you check this, please?

Of course. I must have jumbled something up because this didn't happen in my environment. Ill get it fixed asap.

**Comment by MajesticFalcon** [comment]
@cimnine The test is not failing for me

**Comment by MajesticFalcon** [comment]
I think I see the problem, the tests you are running are against code that I have not even pulled down yet. My repo doesn't even have a cluster_group initializer.

**Comment by MajesticFalcon** [comment]
Rebase gave me cluster groups. Tests now pass including cluster groups in my environment.

**Review by cimnine — APPROVED** [review]

**Comment by cimnine** [comment]
I merged this via CLI in 323e18278aff831fbaa1f47f7548f28e3894711d.

**Pull request closed without merging**
