### PR TITLE
Device type iface init

### PR DESCRIPTION
**Pull request by palmersample**
Related Issue:

## New Behavior

Added startup script and initialization YAML file to support adding interfaces to device types.

...

## Contrast to Current Behavior

New functionality - did not previously exist
...

## Discussion: Benefits and Drawbacks

When initializing device types during startup, adding templated interfaces simplifies later device addition without having to manually add each interface.

Drawbacks: at this time only the interface templates are added (no console, etc.) due to personal requirements

Backwards compatible: yes

Also part of this PR is renumbering the device startup script order to ensure the "platforms" are initialized before devices; this enables device platform definition during startup
...

## Changes to the Wiki

...

## Proposed Release Note Entry

Added device_type_interfaces initialization template and startup script to enable creation of interface templates for device types

...

## Double Check

* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

### CODE REVIEW

**Comment by ryanmerolle** [comment]
Please address the merge conflicts

**Comment by atos-tomasz-fabisiak** [comment]
@palmersample I guess I've added that functionality in #742. It was released in v2.0.0. Have you checked it?

**Comment by kr3ator** [comment]
@palmersample I guess I've added that functionality in https://github.com/netbox-community/netbox-docker/pull/742. It was released in v2.0.0. Have you checked it?

**Comment by tobiasge** [comment]
Initializers are now a plugin.

**Pull request closed without merging**
