### PR TITLE
Updates the configuration, changes default for dynamic paramters to None

### PR DESCRIPTION
**Pull request by cimnine**
Related Issue: #819

## New Behavior

Values, which are now [_dynamic configuration paramters_ according to the docs](https://docs.netbox.dev/en/stable/configuration/#dynamic-configuration-parameters) have their default set to None.
To make this less cumbersome for boolean, int and list values, I've created the new function `_environ_get_and_map` that accepts a lambda as last parameter. I've then created three lambdas for common operations:
- `_AS_INT` (converts a string number value to a python `int`)
- `_AS_BOOL` (converts a string boolean value to a python boolean value, ignoring case)
- `_AS_LIST` (converts a space delimited list of values to a python list of individual string values)

I've also updated our configuration with the latest available parameters from upstream NetBox.

## Contrast to Current Behavior

Some parameters can not be configured at all via environment variables. And some parameters, for which dynamic configuration is available, can not be configured via the web because we always set the value (even if the related environment variable is not defined).

Still, some complex paramaters can't be configured via the environment variable. Our users still have to resort to the `extra.py` mechanism for these values.

## Discussion: Benefits and Drawbacks

With the change, all non-complex configuration paramters can be configured via environment variables again.
The values that are dynamically configurable in theory, for these that become reality also in NetBox Docker.

## Changes to the Wiki

n/a

## Proposed Release Note Entry

All the [_dynamic configuration paramters_](https://docs.netbox.dev/en/stable/configuration/#dynamic-configuration-parameters) can now be configured via the web administration of NetBox. (You can still configure them via environment variables).

The following additional configuration parameters are now available to be configured via environment variables:

- ALLOWED_URL_SCHEMES
- DEVELOPER
- INTERNAL_IPS
- LOGIN_PERSISTENCE
- CSRF_COOKIE_NAME
- SESSION_COOKIE_NAME
- POWERFEED_DEFAULT_AMPERAGE
- POWERFEED_DEFAULT_MAX_UTILIZATION
- POWERFEED_DEFAULT_VOLTAGE

Please refer [to the NetBox documentation](https://docs.netbox.dev/en/stable/configuration/#dynamic-configuration-parameters) for their allowed values and proper use.

## Double Check

* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

### CODE REVIEW

**Comment by tobiasge** [comment]
You are still prevented from setting the configuration values in the UI. I tested it with `PAGINATE_COUNT` which is not in our .env file. I think the problem is, that the configuration code in Netbox checks if the settings have the attribute. See [here](https://github.com/netbox-community/netbox/blob/56d9725c39716c87e1f63b87925f42a787f3ef18/netbox/netbox/config/__init__.py#L54) and [here](https://github.com/netbox-community/netbox/blob/56d9725c39716c87e1f63b87925f42a787f3ef18/netbox/netbox/settings.py#L141).

So as long as a parameter is set we block the UI configuration. We should probably check if environment variables are set before (in our own `configuration.py`):

```python
if 'PAGINATE_COUNT' in environ:
    globals()['PAGINATE_COUNT'] = _environ_get_and_map('PAGINATE_COUNT', None, _AS_INT)
```

**Comment by cimnine** [comment]
> You are still prevented from setting the configuration values in the UI.

I should have had a closer look at that page 🤦.

The solution, that is now implemented, is not pretty and feels more like a workaround. The best would probably be if upstream NetBox would check [here](https://github.com/netbox-community/netbox/blob/56d9725c39716c87e1f63b87925f42a787f3ef18/netbox/netbox/config/__init__.py#L54) whether the value is `None`, and if so, proceeding instead of returning. Since that not the case, this must do.

**Comment by tobiasge** [comment]
> > You are still prevented from setting the configuration values in the UI.
> 
> I should have had a closer look at that page 🤦.
> 
> The solution, that is now implemented, is not pretty and feels more like a workaround. The best would probably be if upstream NetBox would check [here](https://github.com/netbox-community/netbox/blob/56d9725c39716c87e1f63b87925f42a787f3ef18/netbox/netbox/config/__init__.py#L54) whether the value is `None`, and if so, proceeding instead of returning. Since that not the case, this must do.

I think it's build the way it is because `None` is a valid value for some settings.

Why didn't you use `if 'PAGINATE_COUNT' in environ:` for the checks? With the current implementation we have duplicated every variable that is set in the environment.

**Comment by cimnine** [comment]
Good question. Good input. No good answer. I'll probably change it. But not today.

**Comment by cimnine** [comment]
I tried to ignore the findings of gitleaks, to no avail. But since it finds 'our' leaked credentials, we can safely ignore it.

**Comment by tobiasge** [comment]
There some variables that should also have the `if ... in environ` checks:
  - BANNER_LOGIN
  - BANNER_TOP
  - BANNER_BOTTOM
  - NAPALM_USERNAME
  - NAPALM_PASSWORD
  - MAPS_URL

Those are all also dynamic parameters in Netbox. 


> I tried to ignore the findings of gitleaks, to no avail. But since it finds 'our' leaked credentials, we can safely ignore it.

We could try the ignore file in an extra PR, but for now we can safely ignore the warnings.

**Comment by cimnine** [comment]
Ah now I see. I failed to fix them 😔 Need to work on my Regex Skills 😅

**Comment by cimnine** [comment]
> There some variables that should also have the if ... in environ checks:

Replaced the missing ones with the agreed construct.

> We could try the ignore file in an extra PR, but for now we can safely ignore the warnings.

I've removed the commit with the file, since it did not work.

**Review by tobiasge — APPROVED** [review]

**Comment by ryanmerolle** [comment]
LGTM

**Pull request merged**
