### PR TITLE
Version 2.5.0

### PR DESCRIPTION
**Pull request by tobiasge**
# Noteworthy Changes

## Don't create superuser with default credentials #955
To improve security in production environment we don't create a default admin anymore

## Replaced curl with Skopeo in image functions #956
Improved stability for our build process

## Updated to new unit version #951
We are now using Nginx Unit 1.29.1

## docker-entrypoint.sh needs to be updated to run manage.py reindex --lazy after migrations #947
Update indexes on start when needed

## implement extra LDAP user and group filters as requested in #471 #931
Improved the filter settings for LDAP

## Prepend docker.io to image URLs #910
Using the full image name to fixed errors with podman

## Fix Github action warnings #933
Using the modern syntax for Github Actions ENV variables and output

## Using GITHUB_TOKEN for API #932
Updated the build process to use the GITHUB_TOKEN

## Add redis username parameter #929
Redis username can now be set from ENV variables

## Fix syntax of docker compose commands #914
Using modern syntax for `docker compose`

## Added start_period to docker-compose example #913
Added example for the health checks

## Ensure that '*' or 'localhost' is always in ALLOWED_HOSTS #912
Ensures that `ALLOWED_HOSTS` is always set correctly

# Compatibility

This version of NetBox Docker is only compatible with NetBox v3.4.x and above.
For older versions, use [a previous release of NetBox Docker](https://github.com/netbox-community/netbox-docker/releases/).

### CODE REVIEW

**Comment by cimnine** [comment]
> Replaced curl with Skopeo for in image functions #956

There seems to be a word too much in that title

> allways

There's an `l` too much.

**Review by cimnine — APPROVED** [review]

**Comment by tobiasge** [comment]
> > Replaced curl with Skopeo for in image functions #956
> 
> There seems to be a word too much in that title
> 
> > allways
> 
> There's an `l` too much.

Fixed

**Comment by Delta1977** [comment]
in docker-compose.yml Line 65/66:   redis-cache:  image: redis:7-alpine / Docker.io is missing

**Comment by tobiasge** [comment]
> in docker-compose.yml Line 65/66: redis-cache: image: redis:7-alpine / Docker.io is missing

Will be fixed in an upcoming release.

**Pull request merged**
